import { useCallback, useEffect, useMemo, useState } from "react";
import { ClipboardList, Edit3, Plus, ShieldAlert, Trash2 } from "lucide-react";
import { ConsoleDataTable, type ConsoleColumn, type ConsoleFilter } from "../../../components/console/ConsoleDataTable";
import { ConsoleBadge, ConsoleDialog, ConsoleDialogActions, ConsoleField, ConsoleMetrics, ConsoleNotice } from "../../../components/console/ConsoleResource";
import { ConsoleShell } from "../../../components/console/ConsoleShell";
import { api, type AccountAuditResult, type ApiAccount, type ApiReseller } from "../../../lib/api";
import { formatDate } from "../../../lib/format";

type AccountForm = { stockId: string; product: string; variant: string; email: string; buyer: string; resellerId: string; reseller: string; whatsapp: string; profile: string; device: string; startedAt: string; expiresAt: string; duration: string; status: ApiAccount["status"] };
type AccountAction = { type: "delete"; account: ApiAccount } | null;
const emptyForm = (): AccountForm => ({ stockId: "", product: "", variant: "", email: "", buyer: "", resellerId: "", reseller: "", whatsapp: "", profile: "", device: "", startedAt: "", expiresAt: "", duration: "", status: "active" });
function toForm(row: ApiAccount): AccountForm { return { stockId: row.stockId || "", product: row.product || "", variant: row.variant || "", email: row.email || row.loginPhone || "", buyer: row.buyer || "", resellerId: row.resellerId || "", reseller: row.reseller || "", whatsapp: row.whatsapp || "", profile: row.profile || "", device: row.device || "", startedAt: row.startedAt?.slice(0, 16) || "", expiresAt: row.expiresAt?.slice(0, 16) || "", duration: row.duration || "", status: row.status } }
export default function OwnerConsoleAccountsPage() {
  const [accounts, setAccounts] = useState<ApiAccount[]>([]);
  const [resellers, setResellers] = useState<ApiReseller[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<ApiAccount | null | undefined>(undefined);
  const [form, setForm] = useState<AccountForm>(emptyForm);
  const [action, setAction] = useState<AccountAction>(null);
  const [busy, setBusy] = useState(false);
  const [audit, setAudit] = useState<{ account: ApiAccount; data?: AccountAuditResult; loading: boolean } | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); const results = await Promise.allSettled([api.accounts({ view: "overview" }), api.resellers()]); if (results[0].status === "fulfilled") setAccounts(results[0].value); else setError("Manajemen akun gagal dimuat."); if (results[1].status === "fulfilled") setResellers(results[1].value); setLoading(false); }, []);
  useEffect(() => { load().catch(() => setLoading(false)); }, [load]);
  function openCreate() { setEditing(null); setForm(emptyForm()); }
  function openEdit(row: ApiAccount) { setEditing(row); setForm(toForm(row)); }
  async function save() { if (!form.stockId || !form.product || !form.email || !form.startedAt || !form.expiresAt) { setError("Stock ID, produk, identitas, tanggal mulai, dan expiry wajib diisi."); return; } setBusy(true); try { editing ? await api.updateAccount(editing.id, form) : await api.createAccount({ ...form, source: "manual_input" }); setEditing(undefined); setMessage("Managed account berhasil disimpan."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Akun gagal disimpan."); } finally { setBusy(false); } }
  async function openAudit(row: ApiAccount) { setAudit({ account: row, loading: true }); try { const data = await api.accountAudit(row.id); setAudit({ account: row, data, loading: false }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Audit akun gagal dimuat."); setAudit({ account: row, loading: false }); } }
  async function executeAction() { if (!action) return; setBusy(true); try { await api.deleteAccount(action.account.id); setAction(null); setMessage("Akun dihapus melalui flow aman."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Tindakan akun gagal."); } finally { setBusy(false); } }
  const columns = useMemo<Array<ConsoleColumn<ApiAccount>>>(() => [
    { id: "identity", header: "Identitas", value: (row) => row.email || row.loginPhone || "-", sortable: true, cell: (row) => <span className="console-product-cell"><strong>{row.email || row.loginPhone || "-"}</strong><small>{row.profile || "Tanpa profil"}</small></span> },
    { id: "owner", header: "Reseller", value: (row) => row.reseller || row.resellerId || "-", sortable: true, cell: (row) => <span className="console-product-cell"><strong>{row.reseller || "-"}</strong><small>{row.buyer || "Tanpa buyer"}</small></span> },
    { id: "product", header: "Produk", value: (row) => `${row.product} ${row.variant || ""}`, sortable: true, cell: (row) => <span className="console-product-cell"><strong>{row.product}</strong><small>{row.variant || "-"}</small></span> },
    { id: "status", header: "Status", value: (row) => row.status, sortable: true, cell: (row) => <ConsoleBadge tone={row.status === "active" ? "success" : row.status === "expiring" ? "warning" : row.status === "expired" ? "danger" : "muted"}>{row.status}</ConsoleBadge> },
    { id: "expiry", header: "Expiry", value: (row) => row.expiresAt, sortable: true, cell: (row) => formatDate(row.expiresAt) },
    { id: "source", header: "Source", value: (row) => row.source || "-", hideOnMobile: true },
    { id: "actions", header: "Aksi", value: () => "", cell: (row) => <div className="console-row-actions"><button type="button" onClick={() => openAudit(row)} aria-label={`Audit ${row.id}`}><ClipboardList size={14} /></button><button type="button" onClick={() => openEdit(row)} aria-label={`Edit ${row.id}`}><Edit3 size={14} /></button><button type="button" onClick={() => setAction({ type: "delete", account: row })} aria-label={`Hapus ${row.id}`}><Trash2 size={14} /></button></div> },
  ], []);
  const filters = useMemo<Array<ConsoleFilter<ApiAccount>>>(() => [{ id: "status", label: "Status", options: ["active", "expiring", "expired", "replaced", "disabled"].map((value) => ({ label: value, value })), value: (row) => row.status }, { id: "source", label: "Source", options: ["web_order", "manual_input", "assign_daily"].map((value) => ({ label: value, value })), value: (row) => row.source || "" }], []);
  return <ConsoleShell title="Manajemen Akun" description="Pantau ownership, durasi, expiry, dan riwayat akun pelanggan." refreshing={loading} attentionCount={accounts.filter((row) => row.status === "expired").length} systemState={error ? "unknown" : accounts.some((row) => row.status === "expired") ? "warning" : "healthy"} onRefresh={load}>
    <ConsoleMetrics items={[{ label: "Aktif", value: accounts.filter((row) => row.status === "active").length, tone: "success" }, { label: "Expiring", value: accounts.filter((row) => row.status === "expiring").length, tone: "warning" }, { label: "Expired", value: accounts.filter((row) => row.status === "expired").length, tone: "danger" }, { label: "Tanpa reseller", value: accounts.filter((row) => !row.resellerId && !row.reseller).length, tone: "warning" }]} />
    {error ? <ConsoleNotice tone="danger">{error}</ConsoleNotice> : null}{message ? <ConsoleNotice>{message}</ConsoleNotice> : null}
    <section className="console-panel"><div className="console-panel-header"><div><span>Pelanggan</span><h2>Managed accounts</h2></div><div className="console-panel-toolbar-actions"><button type="button" onClick={openCreate}><Plus size={15} /> Tambah manual</button></div></div><ConsoleDataTable rows={accounts} columns={columns} filters={filters} rowKey={(row) => row.id} loading={loading} error={error} initialPageSize={10} /></section>
    {editing !== undefined ? <ConsoleDialog title={editing ? "Edit managed account" : "Tambah managed account"} eyebrow="Ownership" onClose={() => setEditing(undefined)} wide footer={<ConsoleDialogActions onCancel={() => setEditing(undefined)} onConfirm={save} confirmLabel="Simpan akun" busy={busy} />}><div className="console-resource-form-grid"><ConsoleField label="Stock ID"><input value={form.stockId} onChange={(e) => setForm({ ...form, stockId: e.target.value })} /></ConsoleField><ConsoleField label="Produk"><input value={form.product} onChange={(e) => setForm({ ...form, product: e.target.value })} /></ConsoleField><ConsoleField label="Variant"><input value={form.variant} onChange={(e) => setForm({ ...form, variant: e.target.value })} /></ConsoleField><ConsoleField label="Email / nomor login"><input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></ConsoleField><ConsoleField label="Reseller"><select value={form.resellerId} onChange={(e) => { const reseller = resellers.find((row) => row.id === e.target.value); setForm({ ...form, resellerId: e.target.value, reseller: reseller?.username || reseller?.name || "", whatsapp: reseller?.whatsapp || form.whatsapp }); }}><option value="">Tanpa reseller</option>{resellers.map((row) => <option key={row.id} value={row.id}>{row.username || row.name}</option>)}</select></ConsoleField><ConsoleField label="Buyer"><input value={form.buyer} onChange={(e) => setForm({ ...form, buyer: e.target.value })} /></ConsoleField><ConsoleField label="WhatsApp"><input value={form.whatsapp} onChange={(e) => setForm({ ...form, whatsapp: e.target.value })} /></ConsoleField><ConsoleField label="Profil"><input value={form.profile} onChange={(e) => setForm({ ...form, profile: e.target.value })} /></ConsoleField><ConsoleField label="Mulai"><input type="datetime-local" value={form.startedAt} onChange={(e) => setForm({ ...form, startedAt: e.target.value })} /></ConsoleField><ConsoleField label="Expiry"><input type="datetime-local" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /></ConsoleField><ConsoleField label="Durasi"><input value={form.duration} onChange={(e) => setForm({ ...form, duration: e.target.value })} /></ConsoleField><ConsoleField label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ApiAccount["status"] })}>{["active", "expiring", "expired", "replaced", "disabled"].map((value) => <option key={value} value={value}>{value}</option>)}</select></ConsoleField></div><div className="console-privacy-note"><ShieldAlert size={16} /><span>Password, PIN, OTP, reset link, dan household link tidak dimuat oleh overview endpoint dan tidak ditampilkan di form ini.</span></div></ConsoleDialog> : null}
    {audit ? <ConsoleDialog title="Audit akun" eyebrow={audit.account.id} onClose={() => setAudit(null)} wide><div className="console-audit-timeline">{audit.loading ? <p>Memuat timeline...</p> : audit.data?.timeline.length ? audit.data.timeline.map((row) => <article key={row.id}><span /><div><strong>{row.title}</strong><p>{row.detail}</p><small>{formatDate(row.createdAt)} / {row.source}</small></div></article>) : <p>Belum ada timeline audit.</p>}</div></ConsoleDialog> : null}
    {action ? <ConsoleDialog title="Hapus managed account" eyebrow={action.account.id} onClose={() => setAction(null)} footer={<ConsoleDialogActions onCancel={() => setAction(null)} onConfirm={executeAction} confirmLabel="Hapus akun" busy={busy} danger />}><ConsoleNotice tone="danger">Akun akan dihapus melalui endpoint owner. Data historis dan sinkronisasi mengikuti aturan backend yang sekarang.</ConsoleNotice></ConsoleDialog> : null}
  </ConsoleShell>;
}
