export const defaultData = {
  settings: {
    ownerWhatsAppNumber: process.env.OWNER_WHATSAPP_NUMBER || "",
    botPublicUrl: process.env.WHATSAPP_BOT_PUBLIC_URL || "http://127.0.0.1:4174",
    pakasirProject: process.env.PAKASIR_PROJECT || "kavya",
  },
  products: [
    {
      id: "prod-netflix",
      name: "Netflix Premium",
      description: "Akun Netflix bulanan untuk sharing, semi private, dan private.",
      category: "Netflix",
      isActive: true,
      needsProfile: true,
      needsPin: true,
      code: "NET",
      variants: [
        {
          id: "net-1p1u",
          code: "NET-1P1U",
          name: "Sharing 1P1U",
          description: "Sharing 1 profile 1 user.",
          prices: { "1 Bulan": 35000, "2 Bulan": 65000, "3 Bulan": 90000 },
          snk: "Dilarang ubah email, password, dan PIN tanpa izin owner.",
        },
        {
          id: "net-2p1u",
          code: "NET-2U",
          name: "Sharing 2U",
          description: "Sharing slot 2 user dengan pool stok sendiri.",
          prices: { "1 Bulan": 25000, "3 Bulan": 65000 },
          snk: "Gunakan profile sesuai nama buyer.",
        },
        {
          id: "net-semi-private",
          code: "NET-SEMI",
          name: "Semi Private",
          description: "Akun semi private bulanan.",
          prices: { "1 Bulan": 60000, "2 Bulan": 90000, "3 Bulan": 115000 },
          snk: "Ikuti aturan profile dan device dari admin.",
        },
        {
          id: "net-private",
          code: "NET-PRIVATE",
          name: "Private",
          description: "Akun private bulanan.",
          isActive: false,
          prices: { "1 Bulan": 155000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-spotify",
      name: "Spotify Premium",
      description: "Akun Spotify bulanan untuk indplan dan famplan.",
      category: "Spotify",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "SPO",
      variants: [
        {
          id: "spo-indplan",
          code: "SPO-IND",
          name: "Indplan",
          description: "Paket Spotify indplan bulanan.",
          prices: { "1 Bulan": 23000, "2 Bulan": 33000, "3 Bulan": 40000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "spo-famplan",
          code: "SPO-FAM",
          name: "Famplan",
          description: "Paket Spotify famplan bulanan.",
          prices: { "1 Bulan": 18000, "2 Bulan": 25000, "3 Bulan": 30000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-wetv",
      name: "WeTV VIP",
      description: "Akun VIP untuk series Asia.",
      category: "WeTV",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "WETV",
      variants: [
        {
          id: "wetv-vip",
          code: "WETV-VIP",
          name: "VIP Shared",
          description: "Shared login untuk tontonan harian.",
          prices: { "1 Bulan": 18000, "3 Bulan": 50000 },
          snk: "Pemakaian wajar, satu perangkat aktif.",
        },
      ],
    },
    {
      id: "prod-iqiyi",
      name: "iQiyi Premium",
      description: "Premium drama dan anime.",
      category: "iQiyi",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "IQIYI",
      variants: [
        {
          id: "iqiyi-prem",
          code: "IQIYI-PREM",
          name: "Premium",
          description: "Akun premium shared.",
          prices: { "1 Bulan": 20000, "3 Bulan": 55000 },
          snk: "Jangan ubah password.",
        },
      ],
    },
    {
      id: "prod-hbo",
      name: "HBO Max",
      description: "Akun HBO Max bulanan untuk sharing dan private.",
      category: "HBO Max",
      isActive: true,
      needsProfile: true,
      needsPin: true,
      code: "HBO",
      variants: [
        {
          id: "hbo-sharing",
          code: "HBO-SHARE",
          name: "Sharing",
          description: "Paket HBO Max sharing bulanan.",
          prices: { "1 Bulan": 20000, "2 Bulan": 26000, "3 Bulan": 34000 },
          snk: "Gunakan profile yang diberikan admin.",
        },
        {
          id: "hbo-private",
          code: "HBO-PRIVATE",
          name: "Private",
          description: "Paket HBO Max private bulanan.",
          prices: { "1 Bulan": 55000, "2 Bulan": 80000 },
          snk: "Private mengikuti aturan device dari admin.",
        },
      ],
    },
    {
      id: "prod-crunchyroll",
      name: "Crunchyroll",
      description: "Akun Crunchyroll bulanan untuk anime.",
      category: "Crunchyroll",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "CRUNCHY",
      variants: [
        {
          id: "crunchy-sharing",
          code: "CRUNCHY-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 20000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "crunchy-private",
          code: "CRUNCHY-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 35000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-youtube",
      name: "YouTube Premium",
      description: "Paket YouTube Premium bulanan.",
      category: "YouTube",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "YT",
      variants: [
        {
          id: "yt-indplan",
          code: "YT-IND",
          name: "Indplan",
          description: "Paket indplan bulanan.",
          prices: { "1 Bulan": 15000, "3 Bulan": 28000, "4 Bulan": 35000 },
          snk: "Ikuti instruksi login dari admin.",
        },
        {
          id: "yt-famplan",
          code: "YT-FAM",
          name: "Famplan",
          description: "Paket famplan bulanan.",
          prices: { "1 Bulan": 10000, "2 Bulan": 16000, "4 Bulan": 22000, "6 Bulan": 28000 },
          snk: "Ikuti instruksi family invite dari admin.",
        },
        {
          id: "yt-mixplan",
          code: "YT-MIX",
          name: "Mixplan",
          description: "Paket mixplan.",
          prices: { "3 Bulan": 30000, "5 Bulan": 40000, "6 Bulan": 46000 },
          snk: "Ikuti instruksi login dari admin.",
        },
      ],
    },
    {
      id: "prod-disney",
      name: "Disney+",
      description: "Paket Disney+ bulanan.",
      category: "Disney+",
      isActive: true,
      needsProfile: true,
      needsPin: false,
      code: "DISNEY",
      variants: [
        {
          id: "disney-sharing-6u",
          code: "DISNEY-6U",
          name: "Sharing 6U",
          description: "Sharing 6 user bulanan.",
          prices: { "1 Bulan": 32000, "2 Bulan": 55000, "3 Bulan": 73000 },
          snk: "Sharing berarti paham limit.",
        },
        {
          id: "disney-sharing-3u",
          code: "DISNEY-3U",
          name: "Sharing 3U",
          description: "Sharing 3 user bulanan.",
          prices: { "1 Bulan": 55000, "2 Bulan": 95000, "3 Bulan": 135000 },
          snk: "Sharing berarti paham limit.",
        },
        {
          id: "disney-private",
          code: "DISNEY-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 145000 },
          snk: "OTP dan login mengikuti arahan admin.",
        },
      ],
    },
    {
      id: "prod-bstation",
      name: "Bstation",
      description: "Akun Bstation bulanan.",
      category: "Bstation",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "BSTATION",
      variants: [
        {
          id: "bstation-sharing",
          code: "BSTATION-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 15000, "3 Bulan": 20000, "1 Tahun": 30000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "bstation-private",
          code: "BSTATION-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 40000, "3 Bulan": 105000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-prime-video",
      name: "Prime Video",
      description: "Akun Prime Video bulanan.",
      category: "Prime Video",
      isActive: true,
      needsProfile: true,
      needsPin: false,
      code: "PRIME",
      variants: [
        {
          id: "prime-sharing-5u",
          code: "PRIME-5U",
          name: "Sharing 5U",
          description: "Sharing 5 user bulanan.",
          prices: { "1 Bulan": 14000 },
          snk: "Gunakan sesuai slot yang diberikan admin.",
        },
        {
          id: "prime-sharing-3u",
          code: "PRIME-3U",
          name: "Sharing 3U",
          description: "Sharing 3 user bulanan.",
          prices: { "1 Bulan": 20000 },
          snk: "Gunakan sesuai slot yang diberikan admin.",
        },
        {
          id: "prime-sharing-2u",
          code: "PRIME-2U",
          name: "Sharing 2U",
          description: "Sharing 2 user bulanan.",
          prices: { "1 Bulan": 24000 },
          snk: "Gunakan sesuai slot yang diberikan admin.",
        },
        {
          id: "prime-private",
          code: "PRIME-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 30000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-viu",
      name: "Viu",
      description: "Paket Viu private anti-limit bulanan.",
      category: "Viu",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "VIU",
      variants: [
        {
          id: "viu-private-antilimit",
          code: "VIU-PRIVATE",
          name: "Private Anti-Limit",
          description: "Private anti-limit bulanan.",
          prices: { "1 Bulan": 15000, "2 Bulan": 18000, "3 Bulan": 23000, "4 Bulan": 27000, "5 Bulan": 30000, "6 Bulan": 35000, "1 Tahun": 40000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-loklok",
      name: "Loklok",
      description: "Akun Loklok bulanan.",
      category: "Loklok",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "LOKLOK",
      variants: [
        {
          id: "loklok-sharing",
          code: "LOKLOK-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 10000, "3 Bulan": 25000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "loklok-private",
          code: "LOKLOK-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 45000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-apple-tv",
      name: "Apple TV",
      description: "Akun Apple TV bulanan.",
      category: "Apple TV",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "ATV",
      variants: [
        {
          id: "apple-tv-sharing-3u",
          code: "ATV-3U",
          name: "Sharing 3U",
          description: "Sharing 3 user bulanan.",
          prices: { "1 Bulan": 30000 },
          snk: "Gunakan sesuai instruksi admin.",
        },
        {
          id: "apple-tv-private",
          code: "ATV-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 40000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-vidio",
      name: "Vidio",
      description: "Paket Vidio private bulanan.",
      category: "Vidio",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "VIDIO",
      variants: [
        {
          id: "vidio-platinum-tv",
          code: "VIDIO-PLATINUM-TV",
          name: "Platinum TV",
          description: "Platinum untuk device TV.",
          prices: { "1 Bulan": 35000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "vidio-platinum-mobile",
          code: "VIDIO-PLATINUM-MOBILE",
          name: "Platinum Mobile",
          description: "Platinum untuk device mobile.",
          prices: { "1 Bulan": 35000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "vidio-platinum-all-device",
          code: "VIDIO-PLATINUM-ALL",
          name: "Platinum All Device",
          description: "Platinum untuk semua device.",
          prices: { "1 Bulan": 35000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "vidio-diamond-private",
          code: "VIDIO-DIAMOND",
          name: "Diamond Private",
          description: "Diamond private bulanan.",
          prices: { "1 Bulan": 115000 },
          snk: "Tidak boleh mengganti data login.",
          isActive: false,
        },
      ],
    },
    {
      id: "prod-apple-music",
      name: "Apple Music",
      description: "Paket Apple Music bulanan.",
      category: "Apple Music",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "AMUSIC",
      variants: [
        {
          id: "apple-music-giftcard",
          code: "AMUSIC-GIFT",
          name: "Giftcard",
          description: "Giftcard 1-2 bulan.",
          prices: { "1 Bulan": 23000, "2 Bulan": 23000 },
          snk: "Ikuti instruksi redeem dari admin.",
        },
        {
          id: "apple-music-imess",
          code: "AMUSIC-IMESS",
          name: "Via iMessage",
          description: "Apple Music via iMessage bulanan.",
          prices: { "1 Bulan": 25000, "3 Bulan": 40000 },
          snk: "Wajib mengikuti instruksi invite dari admin.",
        },
      ],
    },
    {
      id: "prod-tiktok-music",
      name: "TikTok Music",
      description: "Paket TikTok Music sharing bulanan.",
      category: "TikTok Music",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "TTMUSIC",
      variants: [
        {
          id: "tiktok-music-sharing",
          code: "TTMUSIC-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 15000, "2 Bulan": 20000, "3 Bulan": 27000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-picsart-gold",
      name: "Picsart Gold",
      description: "Paket Picsart Gold bulanan.",
      category: "Picsart",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "PICSART",
      variants: [
        {
          id: "picsart-sharing",
          code: "PICSART-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 10000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "picsart-private",
          code: "PICSART-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 15000, "1 Tahun": 25000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-capcut",
      name: "CapCut",
      description: "Paket CapCut sharing bulanan.",
      category: "CapCut",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "CAPCUT",
      variants: [
        {
          id: "capcut-sharing",
          code: "CAPCUT-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 15000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-canva",
      name: "Canva",
      description: "Paket Canva member bulanan.",
      category: "Canva",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "CANVA",
      variants: [
        {
          id: "canva-member",
          code: "CANVA-MEMBER",
          name: "Member",
          description: "Canva member bulanan.",
          prices: { "1 Bulan": 10000, "2 Bulan": 13000, "3 Bulan": 16000, "4 Bulan": 18000, "6 Bulan": 28000, "1 Tahun": 30000, "Lifetime": 33000 },
          snk: "Akses mengikuti invite admin.",
        },
      ],
    },
    {
      id: "prod-get-contact",
      name: "Get Contact",
      description: "Paket Get Contact private bulanan.",
      category: "Get Contact",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "GETCONTACT",
      variants: [
        {
          id: "get-contact-private",
          code: "GETCONTACT-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 15000 },
          snk: "Customer wajib standby saat proses.",
        },
      ],
    },
    {
      id: "prod-inshot",
      name: "InShot",
      description: "Paket InShot sharing lifetime.",
      category: "InShot",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "INSHOT",
      variants: [
        {
          id: "inshot-sharing",
          code: "INSHOT-SHARE",
          name: "Sharing",
          description: "Paket sharing lifetime.",
          prices: { "Lifetime": 23000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-alight-motion",
      name: "Alight Motion",
      description: "Paket Alight Motion sharing dan private tahunan.",
      category: "Alight Motion",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "ALIGHT",
      variants: [
        {
          id: "alight-sharing",
          code: "ALIGHT-SHARE",
          name: "Sharing",
          description: "Paket sharing tahunan.",
          prices: { "1 Tahun": 16000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "alight-private",
          code: "ALIGHT-PRIVATE",
          name: "Private",
          description: "Paket private tahunan.",
          prices: { "1 Tahun": 20000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-lightroom",
      name: "Lightroom",
      description: "Paket Lightroom sharing tahunan.",
      category: "Lightroom",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "LIGHTROOM",
      variants: [
        {
          id: "lightroom-sharing",
          code: "LIGHTROOM-SHARE",
          name: "Sharing",
          description: "Paket sharing tahunan.",
          prices: { "1 Tahun": 20000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "lightroom-preset",
          code: "LIGHTROOM-PRESET",
          name: "Akun + Preset 2000",
          description: "Paket Lightroom akun plus preset.",
          prices: { "1 Tahun": 25000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-remini",
      name: "Remini",
      description: "Paket Remini sharing tahunan.",
      category: "Remini",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "REMINI",
      variants: [
        {
          id: "remini-lite",
          code: "REMINI-LITE",
          name: "Lite Sharing",
          description: "Paket lite sharing tahunan.",
          prices: { "1 Tahun": 27000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "remini-pro",
          code: "REMINI-PRO",
          name: "Pro Sharing",
          description: "Paket pro sharing tahunan.",
          prices: { "1 Tahun": 32000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-vsco",
      name: "VSCO",
      description: "Paket VSCO sharing tahunan.",
      category: "VSCO",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "VSCO",
      variants: [
        {
          id: "vsco-plus",
          code: "VSCO-PLUS",
          name: "Sharing Plus",
          description: "Paket sharing plus tahunan.",
          prices: { "1 Tahun": 20000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "vsco-pro",
          code: "VSCO-PRO",
          name: "Sharing Pro",
          description: "Paket sharing pro tahunan.",
          prices: { "1 Tahun": 30000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-brainly",
      name: "Brainly",
      description: "Paket Brainly sharing tahunan.",
      category: "Brainly",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "BRAINLY",
      variants: [
        {
          id: "brainly-sharing",
          code: "BRAINLY-SHARE",
          name: "Sharing",
          description: "Paket sharing tahunan.",
          prices: { "1 Tahun": 25000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-scribd",
      name: "Scribd",
      description: "Paket Scribd bulanan.",
      category: "Scribd",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "SCRIBD",
      variants: [
        {
          id: "scribd-sharing",
          code: "SCRIBD-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 15000 },
          snk: "Tidak boleh mengganti data login.",
        },
        {
          id: "scribd-private",
          code: "SCRIBD-PRIVATE",
          name: "Private",
          description: "Paket private bulanan.",
          prices: { "1 Bulan": 20000 },
          snk: "Data login hanya digunakan oleh buyer.",
        },
      ],
    },
    {
      id: "prod-grammarly",
      name: "Grammarly",
      description: "Paket Grammarly sharing bulanan.",
      category: "Grammarly",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "GRAMMARLY",
      variants: [
        {
          id: "grammarly-sharing",
          code: "GRAMMARLY-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 13000, "3 Bulan": 17000, "6 Bulan": 25000, "1 Tahun": 35000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-ms-365",
      name: "Microsoft 365",
      description: "Paket Microsoft 365 sharing bulanan.",
      category: "Microsoft 365",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "MS365",
      variants: [
        {
          id: "ms365-sharing",
          code: "MS365-SHARE",
          name: "Sharing",
          description: "Paket sharing bulanan.",
          prices: { "1 Bulan": 15000 },
          snk: "Tidak boleh mengganti data login.",
        },
      ],
    },
    {
      id: "prod-chatgpt",
      name: "ChatGPT",
      description: "Paket akses ChatGPT bulanan.",
      category: "ChatGPT",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "GPT",
      variants: [
        {
          id: "chatgpt-sharing",
          code: "GPT-SHARE",
          name: "Sharing",
          description: "Akses ChatGPT sharing bulanan.",
          prices: { "1 Bulan": 25000, "3 Bulan": 70000 },
          snk: "Tidak boleh mengganti email, password, atau device tanpa izin admin.",
        },
      ],
    },
    {
      id: "prod-windscribe",
      name: "Windscribe VPN",
      description: "Paket Windscribe VPN bulanan.",
      category: "Windscribe",
      isActive: true,
      needsProfile: false,
      needsPin: false,
      code: "WIND",
      variants: [
        {
          id: "windscribe-sharing",
          code: "WIND-SHARE",
          name: "Sharing",
          description: "Paket sharing Windscribe VPN.",
          prices: { "1 Bulan": 12000, "3 Bulan": 30000, "6 Bulan": 50000 },
          snk: "Gunakan sesuai kuota akun dan jangan ubah kredensial.",
        },
      ],
    },
  ],
  stock: [],
  orders: [],
  resellers: [],
  managedAccounts: [],
  whatsappRentals: [],
  whatsappGroupLists: [],
  whatsappMessages: [],
  payments: [],
  activities: [],
};
