import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarPlus, Edit3, Link2, MessageCircle, Plus, RefreshCw } from "lucide-react";
import { ConsoleDataTable, type ConsoleColumn, type ConsoleFilter } from "../../../components/console/ConsoleDataTable";
import { ConsoleBadge, ConsoleDialog, ConsoleDialogActions, ConsoleField, ConsoleMetrics, ConsoleNotice } from "../../../components/console/ConsoleResource";
import { ConsoleShell } from "../../../components/console/ConsoleShell";
import { api, type WhatsappRental, type WhatsappStatus } from "../../../lib/api";

type RentalForm = { linkGrub: string; owner: string; contact: string; startedAt: string; endsAt: string; status: WhatsappRental["status"] };
const emptyForm = (): RentalForm => ({ linkGrub: "", owner: "", contact: "", startedAt: new Date().toISOString().slice(0, 10), endsAt: "", status: "active" });
function rentalDays(startedAt: string, endsAt: string) { const start = new Date(`${startedAt}T00:00:00`); const end = new Date(`${endsAt}T00:00:00`); return Math.ceil((end.getTime() - start.getTime()) / 86400000); }
function shortDate(value?: string) { if (!value) return "-"; const date = new Date(value.includes("T") ? value : `${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" }); }

export default function OwnerConsoleWhatsappPage() {
  const [groups, setGroups] = useState<WhatsappRental[]>([]);
  const [status, setStatus] = useState<WhatsappStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<WhatsappRental | null | undefined>(undefined);
  const [form, setForm] = useState<RentalForm>(emptyForm);
  const [busy, setBusy] = useState("");
  const [adjusting, setAdjusting] = useState<WhatsappRental | null>(null);
  const [priceSync, setPriceSync] = useState<{ group: WhatsappRental; changes: number; cleanup: number; parsedRows: number } | null>(null);
  const [days, setDays] = useState("30");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [rentals, connection] = await Promise.all([api.whatsappRentals(), api.whatsappStatus()]); setGroups(rentals); setStatus(connection); } catch (cause) { setError(cause instanceof Error ? cause.message : "WhatsApp gagal dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { load().catch(() => undefined); }, [load]);
  function openCreate() { setForm(emptyForm()); setEditing(null); }
  function openEdit(row: WhatsappRental) { setForm({ linkGrub: row.linkGrub || "", owner: row.owner || "", contact: row.contact || "", startedAt: row.startedAt?.slice(0, 10) || "", endsAt: row.endsAt?.slice(0, 10) || "", status: row.status }); setEditing(row); }
  async function save() { const daysLeft = rentalDays(form.startedAt, form.endsAt); if (!form.linkGrub.trim() || !form.owner.trim() || !form.contact.trim() || !form.startedAt || !form.endsAt) { setError("Link grup, nama owner, nomor owner, tanggal mulai, dan tanggal berakhir wajib diisi."); return; } if (!Number.isFinite(daysLeft) || daysLeft <= 0) { setError("Tanggal berakhir harus setelah tanggal mulai."); return; } setBusy("save"); try { const payload = { ...form, name: editing?.name || "", groupJid: editing?.groupJid || "", monthlyPrice: editing?.monthlyPrice || 0, daysLeft }; editing ? await api.updateWhatsappRental(editing.id, payload) : await api.createWhatsappRental(payload); setEditing(undefined); setMessage("Data rental WhatsApp tersimpan."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Rental gagal disimpan."); } finally { setBusy(""); } }
  async function adjust() { if (!adjusting || !Number(days)) return; setBusy("adjust"); try { await api.adjustWhatsappRental(adjusting.id, Number(days)); setAdjusting(null); setMessage("Durasi rental diperbarui."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Durasi gagal diperbarui."); } finally { setBusy(""); } }
  async function previewPriceSync(row: WhatsappRental) { setBusy(row.id); try { const preview = await api.previewWhatsappGroupPriceSync(row); const changes = preview.changes?.length || 0; const cleanup = preview.cleanup?.length || 0; if (!changes && !cleanup) { setMessage(`Tidak ada harga yang perlu diubah. ${preview.parsedRows || 0} baris terbaca.`); return; } setPriceSync({ group: row, changes, cleanup, parsedRows: preview.parsedRows || 0 }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Preview sinkronisasi harga gagal."); } finally { setBusy(""); } }
  async function applyPriceSync() { if (!priceSync) return; setBusy("price-sync"); try { const result = await api.applyWhatsappGroupPriceSync(priceSync.group); setPriceSync(null); setMessage(`${result.updated} harga berhasil diperbarui.`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Sinkronisasi harga gagal."); } finally { setBusy(""); } }
  const columns = useMemo<Array<ConsoleColumn<WhatsappRental>>>(() => [
    { id: "group", header: "Grup", value: (row) => `${row.name} ${row.linkGrub || ""}`, sortable: true, cell: (row) => <span className="console-product-cell"><strong>{row.name}</strong><small>{row.linkGrub || "Link belum tersedia"}</small></span> },
    { id: "owner", header: "Owner", value: (row) => `${row.owner || ""} ${row.contact || ""}`, sortable: true, cell: (row) => <span className="console-product-cell"><strong>{row.owner || "-"}</strong><small>{row.contact || "Nomor belum diisi"}</small></span> },
    { id: "period", header: "Periode", value: (row) => `${row.startedAt || ""} ${row.endsAt || ""}`, sortable: true, cell: (row) => <span className="console-product-cell"><strong>{shortDate(row.startedAt)}</strong><small>sampai {shortDate(row.endsAt)}</small></span> },
    { id: "status", header: "Status", value: (row) => row.status, sortable: true, cell: (row) => <ConsoleBadge tone={row.status === "active" ? "success" : row.status === "expired" ? "danger" : "warning"}>{row.status}</ConsoleBadge> },
    { id: "actions", header: "Aksi", value: () => "", cell: (row) => <div className="console-row-actions"><button type="button" onClick={() => openEdit(row)} aria-label={`Edit ${row.name}`}><Edit3 size={14} /></button><button type="button" onClick={() => { setAdjusting(row); setDays("30"); }} aria-label={`Tambah durasi ${row.name}`}><CalendarPlus size={14} /></button><button type="button" disabled={busy === row.id} onClick={() => previewPriceSync(row)} aria-label={`Sync harga ${row.name}`}><RefreshCw size={14} /></button>{row.linkGrub ? <a href={row.linkGrub} target="_blank" rel="noreferrer" aria-label={`Buka grup ${row.name}`}><Link2 size={14} /></a> : null}</div> },
  ], [busy]);
  const filters = useMemo<Array<ConsoleFilter<WhatsappRental>>>(() => [{ id: "status", label: "Status", options: ["active", "paused", "expired"].map((value) => ({ label: value, value })), value: (row) => row.status }], []);
  return <ConsoleShell title="WhatsApp" description="Kelola koneksi bot dan rental grup aktif." refreshing={loading} systemState={error ? "unknown" : status?.connected ? "healthy" : "warning"} attentionCount={status?.connected ? 0 : 1} onRefresh={load}>
    <ConsoleMetrics items={[{ label: "Koneksi", value: status?.connected ? "Connected" : "Periksa", tone: status?.connected ? "success" : "warning" }, { label: "Rental aktif", value: groups.filter((row) => row.status === "active").length }, { label: "Expired", value: groups.filter((row) => row.status === "expired").length, tone: "danger" }, { label: "Total list", value: groups.reduce((sum, row) => sum + Number(row.listCount || 0), 0) }]} />
    {error ? <ConsoleNotice tone="danger">{error}</ConsoleNotice> : null}{message ? <ConsoleNotice>{message}</ConsoleNotice> : null}
    <section className="console-panel"><div className="console-panel-header"><div><span>Operasional</span><h2>Rental grup</h2></div><div className="console-panel-toolbar-actions"><button type="button" onClick={openCreate}><Plus size={15} /> Tambah rental</button></div></div><ConsoleDataTable rows={groups} columns={columns} filters={filters} rowKey={(row) => row.id} loading={loading} error={error} initialPageSize={10} /></section>
    {editing !== undefined ? <ConsoleDialog title={editing ? "Edit rental" : "Tambah rental"} eyebrow="WhatsApp" onClose={() => setEditing(undefined)} footer={<ConsoleDialogActions onCancel={() => setEditing(undefined)} onConfirm={save} confirmLabel="Simpan rental" busy={busy === "save"} />}><div className="console-resource-form-grid"><ConsoleField label="Link grup"><input type="url" value={form.linkGrub} onChange={(e) => setForm({ ...form, linkGrub: e.target.value })} placeholder="https://chat.whatsapp.com/..." /></ConsoleField><ConsoleField label="Nama owner"><input value={form.owner} onChange={(e) => setForm({ ...form, owner: e.target.value })} /></ConsoleField><ConsoleField label="Nomor owner"><input inputMode="tel" value={form.contact} onChange={(e) => setForm({ ...form, contact: e.target.value })} /></ConsoleField><ConsoleField label="Mulai"><input type="date" value={form.startedAt} onChange={(e) => setForm({ ...form, startedAt: e.target.value })} /></ConsoleField><ConsoleField label="Berakhir"><input type="date" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /></ConsoleField><ConsoleField label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as WhatsappRental["status"] })}><option value="active">Aktif</option><option value="paused">Dijeda</option><option value="expired">Berakhir</option></select></ConsoleField></div><ConsoleNotice>Nama grup dan Group JID diambil otomatis setelah bot bergabung melalui link.</ConsoleNotice></ConsoleDialog> : null}
    {adjusting ? <ConsoleDialog title="Atur durasi rental" eyebrow={adjusting.name} onClose={() => setAdjusting(null)} footer={<ConsoleDialogActions onCancel={() => setAdjusting(null)} onConfirm={adjust} confirmLabel="Simpan durasi" busy={busy === "adjust"} />}><ConsoleField label="Perubahan hari" hint="Gunakan angka negatif untuk mengurangi durasi."><input type="number" value={days} onChange={(e) => setDays(e.target.value)} /></ConsoleField></ConsoleDialog> : null}
    {priceSync ? <ConsoleDialog title="Sinkronisasi harga" eyebrow={priceSync.group.name} onClose={() => setPriceSync(null)} footer={<ConsoleDialogActions onCancel={() => setPriceSync(null)} onConfirm={applyPriceSync} confirmLabel="Terapkan perubahan" busy={busy === "price-sync"} />}><div className="console-confirm-copy"><RefreshCw size={20} /><p>{priceSync.changes} harga akan diperbarui dan {priceSync.cleanup} harga lama akan dibersihkan dari {priceSync.parsedRows} baris yang terbaca.</p></div></ConsoleDialog> : null}
  </ConsoleShell>;
}
