export const SHEET_HEADERS = [
  "ACCOUNT & PASSWORD",
  "PROFIL",
  "TANGGAL",
  "DURASI",
  "EXPIRED",
  "PIN",
  "DEVICE CUSTOMER",
  "SELLER",
  "NOMOR WA",
  "ORDER ID / ID MANUAL",
  "KONDISI AKUN",
  "CATATAN",
  "STOCK ID",
];
export const SIMPLE_ACCOUNT_HEADERS = ["ACCOUNT", "PASSWORD", "TANGGAL", "DURASI", "EXPIRED", "SELLER", "NOMOR WA", "ORDER ID", "CATATAN", "STOCK ID"];
export const UNIVERSAL_ACCOUNT_HEADERS = ["ACCOUNT", "TANGGAL", "DURASI", "EXPIRED", "SELLER", "NOMOR WA", "ORDER ID", "CATATAN", "STOCK ID"];
export const DISNEY_HEADERS = ["Number", "OTP Email", "Nama profil", "TANGGAL", "DURASI", "EXPIRED", "DEVICE", "SELLER", "NOMOR WA", "ORDER ID", "CATATAN", "STOCK ID"];

export const CANVA_SHEET_NAME = "Canva";
export const VIU_SHEET_NAME = "Viu";
export const VIDIO_SHEET_NAME = "Vidio";
export const ORDER_HISTORY_SHEET_NAME = "Order History";
export const ORDER_HISTORY_HEADERS = [
  "WAKTU ORDER",
  "RESELLER",
  "CUSTOMER",
  "PRODUK",
  "VARIAN",
  "DURASI",
  "ACCOUNT",
  "PROFIL",
  "EXPIRED",
  "SHEET",
  "ROW",
  "ORDER ID",
  "STOCK ID",
  "CATATAN",
];

export const CANVA_POOL_HEADERS = ["CANVA LINK", "KUOTA", "TERPAKAI", "SISA", "STATUS", "CATATAN"];
export const CANVA_USAGE_HEADERS = ["EMAIL CUSTOMER", "RESELLER", "NOMOR WA", "TANGGAL BELI", "DURASI", "EXPIRED", "ORDER ID", "PLAN"];
export const LINK_POOL_HEADERS = ["LINK", "KUOTA", "TERPAKAI", "SISA", "STATUS", "CATATAN", "STOCK ID"];
export const LINK_USAGE_HEADERS = ["EMAIL CUSTOMER", "RESELLER", "NOMOR WA", "TANGGAL BELI", "DURASI", "EXPIRED", "ORDER ID", "STOCK ID"];
